### ISSUE TITLE
URL in util.py gives 404 error

### ISSUE THREAD

**Issue by ayssedgrmnci** [eomiso/NLP_text-style-transfer#3]
When I tried to run the project, I encountered an error like "_pickle.UnpicklingError: invalid load key, '<'. - ". But when I examined the code, I saw that "URL = "https://docs.google.com/uc?export=download"" on line 8 in utils.py gives 404 error. Please your help.

**Comment by eomiso** [comment]
Hi, that url is used to download a file from google drive. Back then I've used google drive as a storage for the bert classifier checkpoints. You can see the reference [here](https://stackoverflow.com/a/39225272/11793236).

If you would like to use your local storage you could just simply remove the code where `download_google` is used.

**Comment by ayssedgrmnci** [comment]
Thank you so much. I did what you said, but I think the pickle error is not caused by this, the problem continues.

Traceback (most recent call last):
   File "train.py", line 261, in <module>
     trainer = Trainer()
   File "train.py", line 48, in __init__
     ckpt = torch.load(args.clf_ckpt_path,map_location=lambda storage, loc: storage)
   File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 585, in load
     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
   File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 755, in _legacy_load
     magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

I get this error when I run it on google colab. When I researched I realized that I was getting this error because I was trying to run the pre-trained model. I deleted the caches in the project, but I could not solve the problem. Please your help.
